package maven

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/bazel-contrib/rules_jvm/java/gazelle/private/bazel"
	"github.com/bazel-contrib/rules_jvm/java/gazelle/private/maven/multiset"
	"github.com/bazel-contrib/rules_jvm/java/gazelle/private/types"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/rs/zerolog"
)

// NoExternalImportsError represents the error when no external imports are found.
type NoExternalImportsError struct {
	PackageName string
}

func (e *NoExternalImportsError) Error() string {
	return fmt.Sprintf("no external imports found for %s", e.PackageName)
}

// MultipleExternalImportsError represents the error when multiple possible external imports are found.
type MultipleExternalImportsError struct {
	PackageName      string
	PossiblePackages []string
}

func (e *MultipleExternalImportsError) Error() string {
	return fmt.Sprintf("multiple external imports found for %s; %v", e.PackageName, e.PossiblePackages)
}

type Resolver interface {
	Resolve(pkg types.PackageName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) (label.Label, error)
	ResolveClass(className types.ClassName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) (label.Label, error)
}

// CompileResolver is an optional extension for languages whose compiler needs
// same-package artifacts that are implementation dependencies of the artifact
// selected for an imported symbol. Kotlin top-level functions are one example:
// their public signature may expose types from a dependency jar in the same
// package even though the imported symbol itself has one exact owner.
type CompileResolver interface {
	ResolveCompilePackage(pkg types.PackageName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) ([]label.Label, error)
	CompileCompanions(pkg types.PackageName, selected []label.Label, excludedArtifacts map[string]struct{}, mavenRepositoryName string) []label.Label
}

// resolver finds Maven provided packages by reading the maven_install.json
// file from rules_jvm_external.
type resolver struct {
	data         *multiset.StringMultiSet
	classIndex   map[string]string
	dependencies map[string][]string
	logger       zerolog.Logger
}

// ResolverOption configures a resolver.
type ResolverOption func(*resolverConfig)

type resolverConfig struct {
	installFile string
	indexFile   string
	logger      zerolog.Logger
}

// WithInstallFile sets the path to the maven_install.json lock file.
func WithInstallFile(path string) ResolverOption {
	return func(c *resolverConfig) {
		c.installFile = path
	}
}

// WithIndexFile sets the path to the index file generated by rules_jvm_external.
func WithIndexFile(path string) ResolverOption {
	return func(c *resolverConfig) {
		c.indexFile = path
	}
}

// WithLogger sets the logger for the resolver.
func WithLogger(logger zerolog.Logger) ResolverOption {
	return func(c *resolverConfig) {
		c.logger = logger
	}
}

func NewResolver(opts ...ResolverOption) (Resolver, error) {
	cfg := &resolverConfig{
		logger: zerolog.Nop(),
	}
	for _, opt := range opts {
		opt(cfg)
	}

	r := resolver{
		data:         multiset.NewStringMultiSet(),
		classIndex:   make(map[string]string),
		dependencies: make(map[string][]string),
		logger:       cfg.logger.With().Str("_c", "maven-resolver").Logger(),
	}

	var c lockFile
	var lockFileErr error
	if cfg.installFile != "" {
		c, lockFileErr = loadConfiguration(cfg.installFile)
	}

	var index *IndexFile
	var indexFileErr error
	if cfg.indexFile != "" {
		index, indexFileErr = loadIndex(cfg.indexFile)
		if indexFileErr != nil && !os.IsNotExist(indexFileErr) {
			r.logger.Warn().Err(indexFileErr).Msg("failed to load index file")
		}
	}

	// Warn and return early if neither lock file nor index file is available
	if lockFileErr != nil || c == nil {
		if index == nil {
			if lockFileErr != nil {
				r.logger.Warn().Err(lockFileErr).Msg("not loading maven dependencies")
			} else {
				r.logger.Warn().Msg("no maven install file or index file configured")
			}
			return &r, nil
		}
		// We have an index but no lock file - we can't proceed without the lock file
		// since we need it for dependency coordinates
		r.logger.Warn().Msg("index file available but lock file required for dependency coordinates")
		return &r, nil
	}

	dependencies := c.ListDependencies()

	r.logger.Debug().Int("count", len(dependencies)).Msg("Dependency count")

	// Seed package and class data recorded directly in the lock file. This is the
	// only source when no index file is present.
	for _, depName := range dependencies {
		coords, err := ParseCoordinate(c.GetDependencyCoordinates(depName))
		if err != nil {
			return nil, fmt.Errorf("failed to parse coordinate %v: %w", coords, err)
		}
		artifact := coords.ArtifactString()
		for _, directDepName := range c.ListDirectDependencies(depName) {
			directCoords, err := ParseCoordinate(c.GetDependencyCoordinates(directDepName))
			if err != nil {
				return nil, fmt.Errorf("failed to parse direct dependency coordinate %q: %w", directDepName, err)
			}
			r.dependencies[artifact] = append(r.dependencies[artifact], directCoords.ArtifactString())
		}
		r.dependencies[artifact] = uniqueSortedStrings(r.dependencies[artifact])
		for _, pkg := range c.ListDependencyPackages(depName) {
			r.data.Add(pkg, artifact)
		}
		for _, class := range c.ListDependencyClasses(depName) {
			r.classIndex[class] = artifact
		}
	}

	// Seed package and class data from the index. Every index key is an artifact's
	// versionless coordinate (group:artifact[:extension[:classifier]]); plain,
	// packaging-qualified, and classifier-qualified keys are all seeded the same
	// way, so a class living only in a classifier jar (e.g. test-fixtures) resolves
	// just like any other. Keys are seeded most-qualified first so that, on a class
	// FQCN collision between a plain and a classifier jar, the plain jar's later
	// overwrite wins.
	if index != nil {
		for _, key := range indexKeys(index) {
			coords, err := parseIndexKey(key)
			if err != nil {
				r.logger.Fatal().Err(err).Msg("malformed maven_index.json key")
			}
			r.seedIndexKey(index, key, coords.ArtifactString())
		}
	}

	return &r, nil
}

func uniqueSortedStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	sort.Strings(values)
	out := values[:1]
	for _, value := range values[1:] {
		if value != out[len(out)-1] {
			out = append(out, value)
		}
	}
	return out
}

// indexKeys returns the union of the index's package and class keys, ordered
// most-qualified first so plain coordinates seed last.
func indexKeys(index *IndexFile) []string {
	seen := make(map[string]struct{}, len(index.Classes)+len(index.Packages))
	for key := range index.Classes {
		seen[key] = struct{}{}
	}
	for key := range index.Packages {
		seen[key] = struct{}{}
	}
	keys := make([]string, 0, len(seen))
	for key := range seen {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		ci, cj := strings.Count(keys[i], ":"), strings.Count(keys[j], ":")
		if ci != cj {
			return ci > cj
		}
		return keys[i] < keys[j]
	})
	return keys
}

// seedIndexKey records the packages and classes the index attributes to key,
// mapping them to artifactString (the value passed to the artifact() macro).
func (r *resolver) seedIndexKey(index *IndexFile, key, artifactString string) {
	// Use classes section for split package class-level resolution
	if pkgMap, ok := index.Classes[key]; ok {
		for pkg, classes := range pkgMap {
			// Seed package→artifact mapping so split packages are detected
			// as "multiple providers" rather than "not found"
			if pkg != "" {
				r.data.Add(pkg, artifactString)
			}
			for _, cls := range classes {
				fqcn := cls
				if pkg != "" {
					fqcn = pkg + "." + cls
				}
				r.classIndex[fqcn] = artifactString
			}
		}
	}
	// Use packages section for simple package→artifact lookup
	if packages, ok := index.Packages[key]; ok {
		for _, pkg := range packages {
			r.data.Add(pkg, artifactString)
		}
	}
}

func (r *resolver) Resolve(pkg types.PackageName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) (label.Label, error) {
	owners := r.packageOwners(pkg, excludedArtifacts, mavenRepositoryName)
	filtered := labelsForArtifacts(mavenRepositoryName, owners)

	switch len(filtered) {
	case 0:
		return label.NoLabel, &NoExternalImportsError{PackageName: pkg.Name}

	case 1:
		return filtered[0], nil

	default:
		possible := make([]string, 0, len(filtered))
		for _, l := range filtered {
			possible = append(possible, l.String())
		}
		return label.NoLabel, &MultipleExternalImportsError{
			PackageName:      pkg.Name,
			PossiblePackages: possible,
		}
	}
}

// ResolveCompilePackage resolves a package-only import when its split-package
// owners form one dependency-rooted compile group. The unique root is returned
// first; the remaining labels are its same-package dependency companions.
func (r *resolver) ResolveCompilePackage(pkg types.PackageName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) ([]label.Label, error) {
	owners := r.packageOwners(pkg, excludedArtifacts, mavenRepositoryName)
	switch len(owners) {
	case 0:
		return nil, &NoExternalImportsError{PackageName: pkg.Name}
	case 1:
		return r.labelsForCompileGroup(pkg, owners[0], excludedArtifacts, mavenRepositoryName), nil
	}

	var roots []string
	for _, owner := range owners {
		group := r.samePackageDependencyArtifacts(pkg, owner, excludedArtifacts, mavenRepositoryName)
		if len(group) == len(owners) {
			roots = append(roots, owner)
		}
	}
	if len(roots) != 1 {
		possible := make([]string, 0, len(owners))
		for _, l := range labelsForArtifacts(mavenRepositoryName, owners) {
			possible = append(possible, l.String())
		}
		return nil, &MultipleExternalImportsError{
			PackageName:      pkg.Name,
			PossiblePackages: possible,
		}
	}

	return r.labelsForCompileGroup(pkg, roots[0], excludedArtifacts, mavenRepositoryName), nil
}

// CompileCompanions returns the same-package portion of the Maven dependency
// closure rooted at selected package owners. It never adds an arbitrary split
// owner: the selected artifact must own pkg, and every addition must be both a
// dependency of that owner and an exact owner of pkg itself.
func (r *resolver) CompileCompanions(pkg types.PackageName, selected []label.Label, excludedArtifacts map[string]struct{}, mavenRepositoryName string) []label.Label {
	selectedSet := make(map[label.Label]struct{}, len(selected))
	for _, l := range selected {
		selectedSet[l] = struct{}{}
	}

	owners := r.packageOwners(pkg, excludedArtifacts, mavenRepositoryName)
	seen := make(map[string]struct{}, len(owners))
	var artifacts []string
	for _, owner := range owners {
		if _, ok := selectedSet[LabelFromArtifact(mavenRepositoryName, owner)]; !ok {
			continue
		}
		for _, artifact := range r.samePackageDependencyArtifacts(pkg, owner, excludedArtifacts, mavenRepositoryName) {
			if _, ok := seen[artifact]; ok {
				continue
			}
			seen[artifact] = struct{}{}
			artifacts = append(artifacts, artifact)
		}
	}
	return labelsForArtifacts(mavenRepositoryName, artifacts)
}

func (r *resolver) packageOwners(pkg types.PackageName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) []string {
	v, found := r.data.Get(pkg.Name)
	if !found {
		return nil
	}

	owners := make([]string, 0, len(v))
	for artifact := range v {
		if _, excluded := excludedArtifacts[LabelFromArtifact(mavenRepositoryName, artifact).String()]; excluded {
			continue
		}
		owners = append(owners, artifact)
	}
	sort.Strings(owners)
	return owners
}

func (r *resolver) samePackageDependencyArtifacts(pkg types.PackageName, root string, excludedArtifacts map[string]struct{}, mavenRepositoryName string) []string {
	owners := make(map[string]struct{})
	for _, artifact := range r.packageOwners(pkg, excludedArtifacts, mavenRepositoryName) {
		owners[artifact] = struct{}{}
	}

	visited := make(map[string]struct{})
	stack := []string{root}
	reachableOwners := make(map[string]struct{})
	for len(stack) > 0 {
		artifact := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if _, ok := visited[artifact]; ok {
			continue
		}
		visited[artifact] = struct{}{}
		if _, ok := owners[artifact]; ok {
			reachableOwners[artifact] = struct{}{}
		}
		stack = append(stack, r.dependencies[artifact]...)
	}

	companions := make([]string, 0, len(reachableOwners))
	for artifact := range reachableOwners {
		if artifact != root {
			companions = append(companions, artifact)
		}
	}
	sort.Strings(companions)
	if _, ok := reachableOwners[root]; !ok {
		return companions
	}
	return append([]string{root}, companions...)
}

func (r *resolver) labelsForCompileGroup(pkg types.PackageName, root string, excludedArtifacts map[string]struct{}, mavenRepositoryName string) []label.Label {
	return labelsForArtifacts(mavenRepositoryName, r.samePackageDependencyArtifacts(pkg, root, excludedArtifacts, mavenRepositoryName))
}

func labelsForArtifacts(mavenRepositoryName string, artifacts []string) []label.Label {
	labels := make([]label.Label, 0, len(artifacts))
	for _, artifact := range artifacts {
		labels = append(labels, LabelFromArtifact(mavenRepositoryName, artifact))
	}
	return labels
}

func (r *resolver) ResolveClass(className types.ClassName, excludedArtifacts map[string]struct{}, mavenRepositoryName string) (label.Label, error) {
	artifact, found := r.classIndex[className.FullyQualifiedClassName()]
	if !found {
		// rules_jvm_external intentionally indexes only top-level classes. A named nested
		// class is compiled into the same artifact as its outer class, so use the indexed
		// outer class as its owner when the full source-level name has no entry.
		artifact, found = r.classIndex[className.FullyQualifiedOuterClassName()]
	}
	if !found {
		return label.NoLabel, nil
	}

	if _, excluded := excludedArtifacts[LabelFromArtifact(mavenRepositoryName, artifact).String()]; excluded {
		return label.NoLabel, nil
	}

	return LabelFromArtifact(mavenRepositoryName, artifact), nil
}

func LabelFromArtifact(mavenRepositoryName string, artifact string) label.Label {
	return label.New(mavenRepositoryName, "", bazel.CleanupLabel(artifact))
}
