load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "javaparser",
    srcs = [
        "cpus.go",
        "javaparser.go",
        "prefetch.go",
    ],
    importpath = "github.com/bazel-contrib/rules_jvm/java/gazelle/private/javaparser",
    visibility = ["//java/gazelle:__subpackages__"],
    deps = [
        "//java/gazelle/private/java",
        "//java/gazelle/private/javaparser/proto/gazelle/java/javaparser/v0:gazelle_java_build_v0_go_proto",
        "//java/gazelle/private/servermanager",
        "//java/gazelle/private/sorted_multiset",
        "//java/gazelle/private/sorted_set",
        "//java/gazelle/private/types",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "javaparser_test",
    size = "small",
    srcs = [
        "cpus_test.go",
        "javaparser_test.go",
        "prefetch_test.go",
        "scheduler_test.go",
    ],
    embed = [":javaparser"],
    deps = [
        "//java/gazelle/private/javaparser/proto/gazelle/java/javaparser/v0:gazelle_java_build_v0_go_proto",
        "//java/gazelle/private/types",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
    ],
)
