load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "javaparser",
    srcs = [
        "cache.go",
        "cache_lock_other.go",
        "cache_lock_unix.go",
        "cache_lock_windows.go",
        "cpus.go",
        "javaparser.go",
        "prefetch.go",
    ],
    importpath = "github.com/bazel-contrib/rules_jvm/java/gazelle/private/javaparser",
    visibility = ["//java/gazelle:__subpackages__"],
    deps = [
        "//java/gazelle/private/java",
        "//java/gazelle/private/javaparser/proto/gazelle/java/javaparser/v0:gazelle_java_build_v0_go_proto",
        "//java/gazelle/private/servermanager",
        "//java/gazelle/private/sorted_multiset",
        "//java/gazelle/private/sorted_set",
        "//java/gazelle/private/types",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
    ] + select({
        "@rules_go//go/platform:android": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:darwin": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:ios": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:linux": [
            "@org_golang_x_sys//unix",
        ],
        "@rules_go//go/platform:windows": [
            "@org_golang_x_sys//windows",
        ],
        "//conditions:default": [],
    }),
)

go_test(
    name = "javaparser_test",
    size = "small",
    srcs = [
        "cache_test.go",
        "cpus_test.go",
        "javaparser_test.go",
        "prefetch_test.go",
        "scheduler_test.go",
    ],
    embed = [":javaparser"],
    deps = [
        "//java/gazelle/private/javaparser/proto/gazelle/java/javaparser/v0:gazelle_java_build_v0_go_proto",
        "//java/gazelle/private/types",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//:grpc",
    ],
)
